name: Black auto-formatting
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:  # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
            ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v1
      - run: pip install black
      - run: black --check .
      - name: If needed, commit black changes to a new pull request
        if: failure()
        run: |
          black .
          echo 'Failure'