name: DVC pipeline
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: CML run
        working-directory: ./data_governance_testing
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc pull train.csv

          pip install -r requirements.txt
          dvc repro 
          
          git fetch --prune
          
          dvc metrics diff --show-md main > report.md
          
          # Add figure to the report
          echo "## Feature importance"
          cml-publish feature_importance.png --md >> report.md
          cml-send-comment report.md
      - name: run pytest
        working-directory: ./data_governance_testing
        run: |
          pytest ./tests/pytests.py
